# permissions for end users to view markdownviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: markdownview-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mdview-controller
    app.kubernetes.io/part-of: mdview-controller
    app.kubernetes.io/managed-by: kustomize
  name: markdownview-viewer-role
rules:
- apiGroups:
  - view.kubebuilder-md.practice.tak848.net
  resources:
  - markdownviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - view.kubebuilder-md.practice.tak848.net
  resources:
  - markdownviews/status
  verbs:
  - get
