apiVersion: view.kubebuilder-md.practice.tak848.net/v1
kind: MarkdownView
metadata:
  labels:
    app.kubernetes.io/name: markdownview
    app.kubernetes.io/instance: markdownview-sample
    app.kubernetes.io/part-of: mdview-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mdview-controller
  name: markdownview-sample
spec:
  # TODO(user): Add fields here
